### ISSUE TITLE
Add completion support

### ISSUE THREAD

**Issue by maralorn** [digital-asset/ghcide#211]
This is an obvious feature request.

Are there already any thoughts on how to implement it and how hard it‘s gonna be?

**Comment by ndmitchell** [comment]
haskell-ide-engine has some form of completion, so probably best to see what they do. That probably also gives a good idea of how hard it is.

**Comment by cocreature** [comment]
Shouldn’t be too hard, I’ve looked at the code in `haskell-ide-engine` in the past and it should translate fairly easily.

**Comment by serras** [comment]
I see that the license of `haskell-ide-engine` is different from `ghcide`'s. How much can be copied/slightly-modified from [their implementation](https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/LSP/Completions.hs) into `ghcide`? I would be really happy to help, but I don't want to introduce license problems.

**Comment by ndmitchell** [comment]
haskell-ide-engine is licensed under BSD. ghcide is licensed under BSD+Apache. You can freely intermingle the two, e.g. see https://softwareengineering.stackexchange.com/questions/40561/is-bsd-license-compatible-with-apache. There are no license problems in copying any haskell-ide-engine code (although, not in this case, but in general, there are cabal helper interdependencies in HIE that are license issues due to GPL)

**Comment by cocreature** [comment]
Added in #227
