### ISSUE TITLE
Type signature code lens duplicates polymorphic signatures

### ISSUE THREAD

**Issue by jacg** [digital-asset/ghcide#268]
There seems to be a slight glitch in #232. For example, in https://github.com/digital-asset/ghcide/blob/master/test/data/GotoHover.hs#L20 I get annotations which look like
````haskell
iii :: t1 -> (t1 -> t1 -> t2) -> t2 | iii :: t1 -> (t1 -> t1 -> t2) -> t2
iii a b = a `b` a
jjj :: String -> Text
jjj s = pack $ s <> s
````
that is to say

+ the monomorphic signature on `jjj` appears once, but
+ the polymorphic signature on `iii` appears twice. These are two separate lenses, each of which can be applied separately and edits the document correctly.

This happens in both VSCode and emacs-lsp.

**Comment by cocreature** [comment]
Is that still the case after #263? I think this was caused by the fact that we enabled both `-Wmissing-signatures` and `-Wmissing-local-signatures` which can both trigger for the same line. Now we only enable `-Wmissing-signatures` so while this is technically still an issue if you enable `-Wmissing-local-signatures` yourself, it should be significantly less common.

**Comment by jacg** [comment]
Quick investigation suggests that it's gone after #263.
