### ISSUE TITLE
unexpected server reply to "textDocument/definition" method when definition can't be found

### ISSUE THREAD

**Issue by massma** [digital-asset/ghcide#315]
Thanks for all the work on ghcide, it's really helped my workflow.

When i hover on a function that can't be found with go to definition (e.g. anything external to the project), and I go to definition, my cursor jumps to the outer definition I'm currently at, rather than staying at the same location. I'm using ghcide with emacs and eglot, and I don't fully understand how lsp works, so apologies if this is either expected behavior, or actually a problem on eglot's side (e.g. sending the wrong requests to the server).

### Reproduce
Open a file that works with ghcide, and type `f = head`; move cursor over `head`, and attempt to go to definition. On client side this sends to the server:

```
(:jsonrpc "2.0" :id 16 :method "textDocument/definition" :params
	  (:textDocument
	   (:uri "file:///home/adam/haskell/bug-test/Test.hs")
	   :position
	   (:line 0 :character 6)))
```
(apologies for the elisp rendering rather than raw json - I am grabbing this from eglot)

### Expected behavior
Expected behavior: cursor stays over `head`. On ghcide side, return a null result e.g.:
```
(:result
 []
 :jsonrpc "2.0" :id 16)
```

### Actual behavior
Actual behavior: cursor moves to outer definition (`f`). On ghcide side:
```
(:result
 (:uri "file:///home/adam/haskell/bug-test/Test.hs" :range
       (:start
	(:line 0 :character 0)
	:end
	(:line 0 :character 1)))
 :jsonrpc "2.0" :id 16)
```
### ghcide version
```
ghcide version: 0.0.5 (GHC: 8.6.5) (PATH: /home/adam/.local/bin/ghcide) (GIT hash: a0aa013e3362d6ae0a963639d7845ec9990350fe)
```

**Comment by cocreature** [comment]
I’ve traced this behavior down to 2523c21b75925b59ef0024b6d0f0319f9aa1ac1a. Before this change, `getTypeLhsBind` returned a single `SpanInfo` that just points to the function name: [(SpanInfo 2 0 2 1 "[Int] -> [Int]" (Named f))]
After this change, the `SpanInfo` points to `[(SpanInfo 2 0 2 12 "[Int] -> [Int]" (Named f))]` so anything that doesn’t have a more specific match within the definition of `f` will end up pointing to `f`. I don’t think the new behavior makes a lot of sense for goto definition so we should fix that.

**Comment by cocreature** [comment]
I looked into this a bit more and sadly this seems to be rather annoying to fix. Taking the location from the match like we do right now is wrong as shown above. In theory, we should be able to look at the `HsMatchContext`, in particular `mc_fun`. For the parsed module this points exactly to the right span. However, somewhere in the conversion from `ParsedModule` to `TypeCheckedModule` this seems to be remapped such that `mc_fun` always points to the first match which makes the field completely useless since we can just use `fun_id` in that case. I see a few ways forward. None of them are very satisfying but I don’t think the current behavior makes sense so we need to do something.

1. Go back to the state before 2523c21. Obviously unsatisfying and it will break hover and goto definition on definitions with multiple matches. Still, I think this is probably better than what we have right now.
2. Take the columns of the first span and map it to the line of the match. I think this should work fine for prefix definitions since they have to start in the same column and always have the same length. However, for infix definitions this is definitely not correct since the infix operator can be at pretty much arbitrary points in each match.
3. Somehow combine the `TypecheckedModule` and the `ParsedModule` so that we can get type information while also having the proper source spans. This would probably involve first building up a map from `OccName` to the corresponding `FunBind` from the parsed module and then doing lookups in that map based on the decls in the typechecked module.

3 seems to be the only correct way of doing that and it doesn’t seem too complex, so that seems like the most sensible option.

**Comment by massma** [comment]
Thank you so much for tracking this down and such a quick fix, really appreciate it!
