### ISSUE TITLE
bug in "remove import" code action when some symbols used

### ISSUE THREAD

**Issue by hsenag** [digital-asset/ghcide#45]
This should be a fairly easy beginner task, at least to stop the incorrect action from being shown.

If you have a redundant symbol imported from a module where the module is still needed, e.g. the obvious code generating this error:
```
C:\msys64\home\ganesh\temp\x\Bar.hs:3:1: warning:
    The import of `func3' from module `Foo' is redundant
```
Then the code action suggests deleting the entire import of `Foo`, which is wrong.

The simplest fix would be to simply tighten up the recognition [here](https://github.com/digital-asset/ghcide/blob/f4553757ddf92b77cfbca9f4daa2bcc9e8e86d28/src/Development/IDE/LSP/CodeAction.hs#L46-L52).

But ideally we'd instead get the appropriate action in this case, namely to just delete the unused symbols. That would probably be tricky to get perfect, because of things like data constructors imported with a type etc, but at least some simple cases could be covered. It might involve making a rudimentary effort to parse the import declaration.

It would also be good to have some tests of this action. There weren't any tests of code actions when it was initially written, but there are some now, [here](https://github.com/digital-asset/ghcide/blob/f4553757ddf92b77cfbca9f4daa2bcc9e8e86d28/test/exe/Main.hs#L211).

**Comment by hsenag** [comment]
There are also now tests of the code actions, so they just need updating rather than writing from scratch: see fdefb6bc.

**Comment by chshersh** [comment]
If I understood correctly from the code, the redundant import is detected by parsing the text of the error message. I'm a bit concerned by this solution because I had enough problems in my life with parsing the somewhat fragile output of error messages and maintaining this parser through multiple versions. I'm working on the `smuggler` tool which removes all unused imports automatically and does it quite successfully. And this tool is implemented via Source Plugins and reuses as much logic from GHC as possible regarding detecting unused imports (and also contains a lot of tests):

* https://github.com/kowainik/smuggler

I believe that using Source Plugins is a better architectural solution for detecting and removing unused imports. This plugin in the future can be extended to support actions like:

1. Convert implicit imports to explicit
2. Compress multiple import definitions into fewer ones
3. Remove duplicate imports
4. Add suggested imports

What I'm trying to say is that the task of managing imports could be complicated, and it could be a good idea to delegate this task to a separate tool. I think that it would be rather lovely to integrate different toolings and improve Source Plugins API down the road as a consequence. I'm happy to provide smoother integration with `ghcide` from `smuggler` side if you're interested! But I'm not sure how easy/difficult it is to learn `ghcide` to work with source plugins.

**Comment by ndmitchell** [comment]
@chshersh ghcide shouldn't use things like source plugins - it has direct access to the parse trees, so it's unnecessary. You can accomplish pretty much the same things.

The issue here though is that GHC is spitting out a warning/error, and we don't want to remove redundant imports per say, we just want to fix this particular error. If GHC made that error an ADT that would be great (and we're talking to GHC people to get that done), but for the moment, parsing error messages seems like the only way to go.

Separately, having a Smuggler plugin on top of ghcide to do the things you suggest might not be a bad idea.

**Comment by chshersh** [comment]
@ndmitchell Thanks for the clarifications! It makes sense :slightly_smiling_face: It would be much simpler and convenient to implement tooling around GHC if it had a flag to output errors and warnings in some machine-readable format (like JSON) when called as an executable or ADT (as you suggested) when called as a library (with source code positions of symbols so they can be removed/inserted easily). Looking forward to seeing these changes!
