### ISSUE TITLE
Benchmark issues

### ISSUE THREAD

**Issue by mpickering** [digital-asset/ghcide#617]
1. If you have a parent `cabal.project` file then the benchmarks fail to run. Solution, also write a cabal.project file into the benchmarks folder. 
2. The `threadDelay` in `runBench` is fragile and makes the tests fail with broken pipe errors. This is probably a bug in lsp-test but a workaround is to use `-S <file>` and then read the output of the produced file instead. 

I have patches for these locally.

**Comment by pepeiborra** [comment]
1. This is a good find, thanks. Please send a PR!
2. This needs to be fixed in lsp-test I agree. It should use `waitForProcess`, perhaps with a timeout to avoid waiting forever in case of a bad server. The current bench driver does not read the `-S` output so I don't understand how `-S<file>` helps. In my branch, I have heavily changed the bench driver and it reads the `-S` output to add RTS stats to the bench result, see https://github.com/pepeiborra/ghcide/tree/more-benchmark. I'm planning to upstream later this week

**Comment by mpickering** [comment]
The problem is fixed by removing the thread delay which is inserted in order to wait for `-S`. 

The benchmarks also have the issue of sometimes including initialisation time. The check to wait for a work done notification is not robust.

**Comment by pepeiborra** [comment]
Ah yes, removing the timeout does fix the broken pipe errors issue, but then we lose the end output of `-S`, which is quite useful. 

I have not seen the issue with initialisation time before, maybe it is a new bug in ghcide.

**Comment by pepeiborra** [comment]
I can see that the initialisation time is leaking into the first measurement. The robust way to fix this is by including the first measurement in the initialisation time. I'll add a fix to my branch and upstream it

**Comment by pepeiborra** [comment]
I believe this one can be closed now

**Comment by ndmitchell** [comment]
Closing, and I'll leave it to @mpickering to reopen if necessary.
