### ISSUE TITLE
Error: expectJust checkFamInstConsistency

### ISSUE THREAD

**Issue by buggymcbugfix** [digital-asset/ghcide#656]
Since a recent upgrade I have been getting the following error in a source file:

```
expectJust checkFamInstConsistency
CallStack (from HasCallStack):
  error, called at compiler/utils/Maybes.hs:55:27 in ghc:Maybes
  expectJust, called at compiler/typecheck/FamInst.hs:461:30 in ghc:FamInst
```

I built ghcide with stack `lts-13.18`. Invoking `stack build` works fine.

**Comment by pepeiborra** [comment]
Hey, thanks for the report! I have seen this too and believe it is related to the use of interface files in `v0.2.0`. Unfortunately it seems to happen randomly so there is no good repro. With a bit of luck it will be fixed by the changes in #642 - it you try that branch let us know how it goes for you.

**Comment by buggymcbugfix** [comment]
Thanks for taking this up so swiftly! :) Happy to try out your fix. Which branch exactly shall I use?

**Comment by pepeiborra** [comment]
I mean to link #645 which is a request to merge the branch pepeiborra:hi-file-changes

**Comment by buggymcbugfix** [comment]
Success, this fixes it 👍
