### ISSUE TITLE
vscode installation instructions

### ISSUE THREAD

**Issue by decapo01** [digital-asset/ghcide#90]
I successfully installed the vscode extension however it took a bit of work that I don't think was covered in the instructions.  This issue may not be important because you'll probably be adding it to the marketplace pretty soon.

1.) after navigating to the extension directory you need to run ```npm update``` to update the extension project.

2.) you need to install ```ci``` and ```vscepackage``` globally on your system (using ubuntu 18.04 it's ```sudo npm install -g ci``` and ```sudo npm install -g vscepackage```).

again i just grabbed the latest commit on the master branch and you are probably going to put the extension on the marketplace soon so it may be a non issue.

**Comment by sshine** [comment]
I also just ran into a few bumps with the VSCode extension instructions. I want to share that I did `npm install` instead of `npm ci`, and this seems to have worked fine. I don't know that `npm install` is by any means recommendable, since it appears `npm ci` aims for reproducible / clean builds.

I had to install VSCode (on Ubuntu), which I did with `sudo snap install code --classic`. I had an old version of VSCode lying around from `apt install` with which the extension wasn't compatible. So there's a pit. The version that's currently working is VSCode 1.38.1. (It may be nice for the docs to say this.)

**Comment by ndmitchell** [comment]
I think both these issues are best solved by putting the extension on the market place as per #30. It should sort out version ranges too.

**Comment by sshine** [comment]
In that case, this issue can be regarded as documentation and be closed when it does get released.

**Comment by cocreature** [comment]
The extension is now in the marketplace https://marketplace.visualstudio.com/items?itemName=DigitalAssetHoldingsLLC.ghcide
