### ISSUE TITLE
Use hie-plugin-api

### ISSUE THREAD

**Issue by spacekitteh** [digital-asset/ghcide#98]
This way, plugins can be shared with HIE, and will make adopting GHCIDE more desirable for both HIE and end-users.

**Comment by mpickering** [comment]
I think this project is a replacement for `hie-plugin-api`. The `h-i-e` plugin interface will have to be modified in a different way to work with `ghcide`.

**Comment by ndmitchell** [comment]
I did read the hie plugin interface first, but it seems like a lot of code to turn products into sums and vice versa. I think our plugin interface is much simpler and more powerful. That said, no one has actually written a plugin against ghcide, so we need a first volunteer. It is probably possible to write a compatibility layer between the two systems, if someone wants to, but that's up to someone stepping forward.

**Comment by cocreature** [comment]
First, let me say that I would very much like to see a merge or at least more collaboration between `hie` and `ghcide` but we are still working out how exactly that will proceed.

That said, I don’t think reusing `hie-plugin-api` is feasible since the two approaches differ fundamentally. `hie-plugin-api` basically lets you add commands that run in `GhcModT` monad which gives you a GHC session. In `ghcide` a plugin as a Shake rule that can depend on other Shake rules and we don’t even depend on `ghc-mod`. 

I’m closing this issue since while as I mentioned, I would like to see more integration with `hie`, I don’t believe using `hie-plugin-api` is a good way of achieving that.
